import type { FragranceFamily, Intensity, Product } from "@/data/products"

export type ShoppingFor="myself"|"gift"|"exploring"
export type FinderIntensity="light"|"balanced"|"bold"
export type Occasion="everyday"|"confidence"|"date-night"|"after-dark"|"special"|"escape"
export type ScentFinderAnswers={shoppingFor:ShoppingFor|null;families:FragranceFamily[];notes:string[];intensity:FinderIntensity|null;occasions:Occasion[]}
export type ProductMatch={product:Product;percentage:number;reason:string;score:number}
export type ScentProfileResult={name:string;description:string;families:FragranceFamily[];notes:string[];intensity:FinderIntensity|null;occasions:Occasion[];answers:ScentFinderAnswers;matches:ProductMatch[]}
export const emptyFinderAnswers:ScentFinderAnswers={shoppingFor:null,families:[],notes:[],intensity:null,occasions:[]}
export const occasionLabels:Record<Occasion,string>={everyday:"Everyday Ease",confidence:"Quiet Confidence","date-night":"Date Night","after-dark":"After Dark",special:"Special Moments",escape:"Weekend Escape"}
const intensityMap:Record<FinderIntensity,Intensity>={light:"Light",balanced:"Moderate",bold:"Strong"}
const occasionTraits:Record<Occasion,{families:FragranceFamily[];intensities:Intensity[];collections:string[]}>= {
 everyday:{families:["Fresh","Citrus","Floral"],intensities:["Light","Moderate"],collections:["Daylight","Elements"]},confidence:{families:["Woody","Floral"],intensities:["Moderate"],collections:["Quiet Luxury","Elements"]},"date-night":{families:["Amber","Floral"],intensities:["Moderate","Strong"],collections:["After Dark","Nocturne"]},"after-dark":{families:["Amber","Oud","Woody"],intensities:["Strong"],collections:["After Dark"]},special:{families:["Floral","Amber"],intensities:["Moderate","Strong"],collections:["Nocturne","After Dark"]},escape:{families:["Fresh","Citrus"],intensities:["Light","Moderate"],collections:["Daylight","Elements"]},
}
const allNotes=(p:Product)=>[...p.topNotes,...p.heartNotes,...p.baseNotes]
export function recommendationNotes(products:Product[]){const counts=new Map<string,number>();for(const p of products.filter(product=>!product.setCount))for(const note of allNotes(p))counts.set(note,(counts.get(note)??0)+1);return [...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,14).map(([note])=>note)}
export function calculateMatches(products:Product[],answers:ScentFinderAnswers):ProductMatch[]{return products.filter(product=>!product.setCount).map(product=>{let score=8,max=8;const reasons:string[]=[];if(answers.families.length){max+=36;if(answers.families.includes(product.fragranceFamily)){score+=36;reasons.push(`${product.fragranceFamily} character`)}}if(answers.notes.length){max+=Math.min(answers.notes.length,4)*12;const overlap=answers.notes.filter(n=>allNotes(product).includes(n));score+=Math.min(overlap.length,4)*12;if(overlap.length)reasons.push(overlap.slice(0,2).join(" and "))}if(answers.intensity){max+=20;if(product.intensity===intensityMap[answers.intensity]){score+=20;reasons.push(`${product.intensity.toLowerCase()} intensity`)}else if(answers.intensity==="balanced"){score+=8}}if(answers.occasions.length){max+=24;const occasionScore=Math.max(...answers.occasions.map(o=>{const t=occasionTraits[o];return (t.families.includes(product.fragranceFamily)?8:0)+(t.intensities.includes(product.intensity)?7:0)+(t.collections.includes(product.collection)?9:0)}));score+=occasionScore;if(occasionScore>=15)reasons.push(occasionLabels[answers.occasions[0]].toLowerCase())}score+=(product.isFeatured?2:0)+(product.rating>=4.8?1:0);const percentage=Math.max(48,Math.min(97,Math.round(48+(score/max)*49)));const reason=reasons.length?`${product.name} aligns with your preference for ${reasons.slice(0,3).join(", ")}.`:`${product.name} offers a balanced path through the preferences you shared.`;return {product,percentage,reason,score}}).sort((a,b)=>b.score-a.score||b.product.rating-a.product.rating)}
export function createScentProfile(products:Product[],answers:ScentFinderAnswers):ScentProfileResult{const matches=calculateMatches(products,answers),primary=answers.families[0]??matches[0]?.product.fragranceFamily??"Floral",secondary=answers.families[1],tone=answers.intensity==="bold"?"Rich":answers.intensity==="light"?"Soft":"Refined",name=secondary?`${primary} & ${secondary}`:`${tone} ${primary}`;return {name,description:`You’re drawn to ${primary.toLowerCase()} fragrances${secondary?` with a ${secondary.toLowerCase()} edge`:""}. Your strongest matches balance the notes and moments you chose with a ${answers.intensity??"balanced"} presence.`,families:answers.families.length?answers.families:[primary],notes:answers.notes,intensity:answers.intensity,occasions:answers.occasions,answers,matches}}
