"use client"
import {create} from "zustand"
import {createJSONStorage,persist} from "zustand/middleware"
import {products,type Concentration,type FragranceFamily,type Intensity,type ProductImages} from "@/data/products"
export type AdminVariant={id:string;volume:string;price:number;compareAtPrice?:number;sku:string;stock:number;lowStockThreshold:number;active:boolean}
export type AdminProduct={id:string;name:string;slug:string;subtitle:string;description:string;family:FragranceFamily;concentration:Concentration;intensity:Intensity;topNotes:string[];heartNotes:string[];baseNotes:string[];occasions:string[];images:ProductImages;variants:AdminVariant[];collections:string[];status:"Active"|"Draft";featured:boolean;newArrival:boolean;bestSeller:boolean;badge?:string;createdAt:string;updatedAt:string}
export type InventoryEvent={id:string;productId:string;variantId:string;previousStock:number;adjustment:number;newStock:number;reason:string;createdAt:string;adminId:string}
export type Promotion={id:string;code:string;description:string;type:"percentage"|"fixed";value:number;minimumOrder?:number;startDate:string;endDate:string;usageLimit?:number;status:"Active"|"Inactive"|"Scheduled"|"Expired"}
const seeded:AdminProduct[]=products.filter(p=>Boolean(p.images.catalog)).map((p,i)=>({id:p.id,name:p.name,slug:p.slug,subtitle:p.subtitle,description:p.description,family:p.fragranceFamily,concentration:p.concentration,intensity:p.intensity,topNotes:p.topNotes,heartNotes:p.heartNotes,baseNotes:p.baseNotes,occasions:p.collection==="After Dark"?["After Dark","Date Night"]:["Everyday Ease"],images:p.images,variants:p.sizes.map((s,j)=>({id:`${p.id}-v${j+1}`,volume:s.volume,price:s.price,sku:`AUR-${p.slug.slice(0,3).toUpperCase()}-${s.volume.replace(/\D/g,"")}`,stock:s.inStock?((i+j)%9)+3:0,lowStockThreshold:4,active:true})),collections:[p.collection,...(p.isNew?["New Arrivals"]:[]),...(p.isBestSeller?["Best Sellers"]:[])],status:"Active",featured:p.isFeatured,newArrival:p.isNew,bestSeller:p.isBestSeller,createdAt:new Date(2026,0,i+1).toISOString(),updatedAt:new Date().toISOString()}))
type AdminState={products:AdminProduct[];events:InventoryEvent[];promotions:Promotion[];settings:{storeName:string;currency:"NGN";supportEmail:string;defaultLowStockThreshold:number};saveProduct:(product:AdminProduct)=>void;deleteProduct:(id:string)=>void;duplicateProduct:(id:string)=>void;adjustStock:(productId:string,variantId:string,adjustment:number,reason:string)=>boolean;savePromotion:(promotion:Promotion)=>void;toggleCollection:(productId:string,collection:string)=>void;updateSettings:(settings:AdminState["settings"])=>void}
export const useAdminStore=create<AdminState>()(persist((set,get)=>({products:seeded,events:[],promotions:[{id:"promo-welcome",code:"AUREVIA10",description:"Development welcome offer",type:"percentage",value:10,startDate:"2026-01-01",endDate:"2027-01-01",status:"Active"}],settings:{storeName:"Aurévia",currency:"NGN",supportEmail:"support@aurevia.example",defaultLowStockThreshold:4},saveProduct:product=>set(s=>({products:s.products.some(p=>p.id===product.id)?s.products.map(p=>p.id===product.id?{...product,updatedAt:new Date().toISOString()}:p):[{...product,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},...s.products]})),deleteProduct:id=>set(s=>({products:s.products.filter(p=>p.id!==id)})),duplicateProduct:id=>{const p=get().products.find(x=>x.id===id);if(!p)return;const stamp=Date.now();set(s=>({products:[{...p,id:`${p.id}-copy-${stamp}`,name:`${p.name} Copy`,slug:`${p.slug}-copy-${stamp}`,status:"Draft",variants:p.variants.map(v=>({...v,id:`${v.id}-${stamp}`,sku:`${v.sku}-COPY`}))},...s.products]}))},adjustStock:(productId,variantId,adjustment,reason)=>{const p=get().products.find(x=>x.id===productId),v=p?.variants.find(x=>x.id===variantId);if(!p||!v||v.stock+adjustment<0)return false;const next=v.stock+adjustment,event={id:crypto.randomUUID(),productId,variantId,previousStock:v.stock,adjustment,newStock:next,reason,createdAt:new Date().toISOString(),adminId:"development-admin"};set(s=>({products:s.products.map(x=>x.id===productId?{...x,variants:x.variants.map(y=>y.id===variantId?{...y,stock:next}:y),updatedAt:new Date().toISOString()}:x),events:[event,...s.events].slice(0,50)}));return true},savePromotion:promotion=>set(s=>({promotions:s.promotions.some(p=>p.id===promotion.id)?s.promotions.map(p=>p.id===promotion.id?promotion:p):[promotion,...s.promotions]})),toggleCollection:(productId,collection)=>set(s=>({products:s.products.map(p=>p.id===productId?{...p,collections:p.collections.includes(collection)?p.collections.filter(c=>c!==collection):[...p.collections,collection]}:p)})),updateSettings:settings=>set({settings})}),{name:"aurevia-admin-development",version:6,storage:createJSONStorage(()=>localStorage),migrate:persisted=>({...persisted as AdminState,products:seeded})}))
export const inventoryStatus=(v:AdminVariant)=>v.stock===0?"Out of Stock":v.stock<=v.lowStockThreshold?"Low Stock":"In Stock"
