"use client"
import {zodResolver} from "@hookform/resolvers/zod"
import Link from "next/link"
import {useSearchParams} from "next/navigation"
import {useState} from "react"
import {useForm} from "react-hook-form"
import {Button} from "@/components/ui/button"
import {Input} from "@/components/ui/input"
import {Label} from "@/components/ui/label"
import {Textarea} from "@/components/ui/textarea"
import {contactSchema,contactSubjects,type ContactValues} from "@/lib/validations/contact"
const subjectMap:Record<string,ContactValues["subject"]>={returns:"Returns","order-help":"Order Help",delivery:"Delivery","product-question":"Product Question","fragrance-advice":"Fragrance Advice","account-help":"Account Help",other:"Other"}
export function ContactForm(){const search=useSearchParams(),requested=subjectMap[search.get("subject")??""]??"Other",safeOrder=(search.get("order")??"").replace(/[^A-Za-z0-9-]/g,"").slice(0,40),[sent,setSent]=useState(false),{register,handleSubmit,formState:{errors,isSubmitting}}=useForm<ContactValues>({resolver:zodResolver(contactSchema),defaultValues:{name:"",email:"",subject:requested,orderNumber:safeOrder,message:""}});async function submit(){await new Promise(r=>setTimeout(r,500));setSent(true)}if(sent)return <div role="status" className="bg-aurevia-cream p-8"><p className="text-eyebrow text-aurevia-gold">Message prepared successfully</p><h2 className="mt-3 font-display text-4xl text-primary">Thanks for reaching out.</h2><p className="mt-4 leading-7 text-muted-foreground">We&apos;ve received your message in the current support flow. A production helpdesk will replace this development boundary later.</p><Button asChild className="mt-6"><Link href="/help">Return to Help Centre</Link></Button></div>;return <form onSubmit={handleSubmit(submit)} noValidate className="space-y-5"><Field label="Name" id="name" error={errors.name?.message}><Input id="name" autoComplete="name" {...register("name")}/></Field><Field label="Email" id="email" error={errors.email?.message}><Input id="email" type="email" autoComplete="email" {...register("email")}/></Field><div><Label htmlFor="subject">Subject</Label><select id="subject" className="mt-2 h-11 w-full rounded-md border bg-white px-3" {...register("subject")}>{contactSubjects.map(x=><option key={x}>{x}</option>)}</select>{errors.subject&&<p role="alert" className="mt-1 text-sm text-destructive">{errors.subject.message}</p>}</div><Field label="Order Number (optional)" id="orderNumber" error={errors.orderNumber?.message}><Input id="orderNumber" {...register("orderNumber")}/></Field><div><Label htmlFor="message">Message</Label><Textarea id="message" rows={7} className="mt-2" {...register("message")}/>{errors.message&&<p role="alert" className="mt-1 text-sm text-destructive">{errors.message.message}</p>}</div><Button type="submit" size="lg" disabled={isSubmitting}>{isSubmitting?"Preparing message…":"Send Message"}</Button></form>}
function Field({label,id,error,children}:{label:string;id:string;error?:string;children:React.ReactNode}){return <div><Label htmlFor={id}>{label}</Label><div className="mt-2">{children}</div>{error&&<p role="alert" className="mt-1 text-sm text-destructive">{error}</p>}</div>}
