"use client"
import {Bell,Boxes,Gift,LayoutDashboard,LogOut,Menu,Package,Settings,ShoppingBag,Store,Users} from "lucide-react"
import Image from "next/image"
import Link from "next/link"
import {usePathname} from "next/navigation"
import {signOut} from "next-auth/react"
import {useState,type ReactNode} from "react"
import {Button} from "@/components/ui/button"
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetTrigger} from "@/components/ui/sheet"
import {useNotificationStore} from "@/store/notification-store"
const links=[[LayoutDashboard,"Dashboard","/admin"],[Package,"Products","/admin/products"],[Boxes,"Inventory","/admin/inventory"],[ShoppingBag,"Orders","/admin/orders"],[Users,"Customers","/admin/customers"],[Gift,"Promotions","/admin/promotions"],[Settings,"Settings","/admin/settings"]] as const
function Nav(){const path=usePathname();return <nav aria-label="Admin navigation" className="flex flex-col gap-1">{links.map(([Icon,label,href])=>{const active=path===href||(href!=="/admin"&&path.startsWith(href));return <Link key={href} href={href} aria-current={active?"page":undefined} className={`flex min-h-11 items-center gap-3 px-4 text-sm font-semibold ${active?"bg-aurevia-cream text-primary":"text-aurevia-ivory/75 hover:text-white"}`}><Icon className={`size-4 ${active?"text-aurevia-gold":""}`}/>{label}</Link>})}<Link href="/home" className="mt-4 flex min-h-11 items-center gap-3 border-t border-white/10 px-4 pt-4 text-sm font-semibold text-aurevia-ivory/75"><Store className="size-4"/>View Store</Link><button onClick={()=>signOut({callbackUrl:"/sign-in"})} className="flex min-h-11 items-center gap-3 px-4 text-left text-sm font-semibold text-aurevia-ivory/75"><LogOut className="size-4"/>Sign Out</button></nav>}
export function AdminShell({children}:{children:ReactNode}){const notifications=useNotificationStore(s=>s.notifications).filter(n=>n.audience==="ADMIN"),markRead=useNotificationStore(s=>s.markRead),[open,setOpen]=useState(false),unread=notifications.filter(n=>!n.read).length;return <div className="min-h-screen bg-aurevia-ivory lg:grid lg:grid-cols-[15rem_1fr]"><aside className="hidden bg-aurevia-plum p-5 lg:block"><Link href="/admin"><Image src="/images/aurevia-logo.png" alt="Aurévia Admin" width={2172} height={724} className="mb-9 h-auto w-40"/></Link><Nav/></aside><div><header className="relative flex h-16 items-center justify-between border-b px-5 lg:justify-end"><span className="font-display text-2xl text-primary lg:hidden">AURÉVIA ADMIN</span><div className="flex items-center gap-2"><button aria-label={`Admin notifications, ${unread} unread`} onClick={()=>setOpen(v=>!v)} className="relative flex size-10 items-center justify-center border"><Bell className="size-5"/>{unread>0&&<span className="absolute -right-1 -top-1 min-w-5 rounded-full bg-aurevia-plum px-1 text-xs text-white">{unread}</span>}</button><Sheet><SheetTrigger asChild><Button variant="outline" size="icon" className="lg:hidden"><Menu/></Button></SheetTrigger><SheetContent side="left" className="bg-aurevia-plum p-5 text-aurevia-ivory"><SheetHeader><SheetTitle className="text-aurevia-ivory">Admin navigation</SheetTitle></SheetHeader><Nav/></SheetContent></Sheet></div>{open&&<div className="absolute right-5 top-14 z-50 max-h-96 w-[min(24rem,calc(100vw-2.5rem))] overflow-y-auto border bg-white p-3 shadow-xl">{notifications.length?notifications.map(n=><Link key={n.id} href={n.orderId?`/admin/orders/${n.orderId}`:"/admin"} onClick={()=>{markRead(n.id);setOpen(false)}} className="block border-b p-3 last:border-0"><strong className="block text-primary">{n.title}</strong><span className="mt-1 block text-sm text-muted-foreground">{n.message}</span><span className="mt-2 block text-xs text-muted-foreground">{new Date(n.createdAt).toLocaleString()}</span></Link>):<p className="p-4 text-sm text-muted-foreground">No admin notifications yet.</p>}</div>}</header><main className="min-w-0 p-5 sm:p-8 lg:p-10">{children}</main></div></div>}
