"use client"
import Image from "next/image"
import Link from "next/link"
import {Button} from "@/components/ui/button"
import {products} from "@/data/products"
import {occasionLabels} from "@/lib/scent-finder"
import {useAccountStore} from "@/store/account-store"
import {useScentFinderStore} from "@/store/scent-finder-store"
export function ScentProfileContent(){const profile=useAccountStore(s=>s.scentProfile),reset=useScentFinderStore(s=>s.reset);if(!profile)return <div className="flex min-h-[55vh] items-center justify-center text-center"><div className="max-w-xl"><p className="text-eyebrow text-aurevia-gold">Your preferences</p><h1 className="text-display mt-3 text-primary">Your scent profile starts with you.</h1><p className="mt-5 leading-7 text-muted-foreground">Answer five quick questions and we&apos;ll identify the fragrance families and notes you naturally gravitate toward.</p><Button asChild className="mt-7"><Link href="/fragrance-finder">Find My Scent</Link></Button></div></div>;const recommendations=profile.recommendedProductIds.map(id=>products.find(p=>p.id===id)).filter(Boolean);return <div><p className="text-eyebrow text-aurevia-gold">Your scent profile</p><h1 className="text-display mt-3 text-primary">{profile.name}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">{profile.description}</p><dl className="mt-10 grid gap-6 border-y py-7 sm:grid-cols-2 lg:grid-cols-4"><Item label="Families" value={profile.answers.families.join(" · ")}/><Item label="Notes" value={profile.answers.notes.join(" · ")||"Open to discovery"}/><Item label="Intensity" value={profile.answers.intensity??"Balanced"}/><Item label="Moments" value={profile.answers.occasions.map(o=>occasionLabels[o]).join(" · ")}/></dl><p className="mt-4 text-sm text-muted-foreground">Last updated {new Intl.DateTimeFormat("en-NG",{dateStyle:"long"}).format(new Date(profile.updatedAt))}</p><div className="mt-12"><p className="text-eyebrow text-aurevia-gold">Selected for you</p><h2 className="mt-2 font-display text-4xl text-primary">Your recommendations</h2></div><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{recommendations.slice(0,6).map(p=>p&&<Link key={p.id} href={`/product/${p.slug}`} className="group"><div className="relative aspect-[4/5] overflow-hidden bg-aurevia-cream"><Image src={p.image} alt={`${p.name} perfume`} fill sizes="(max-width:640px) 100vw,33vw" className="object-cover transition-transform group-hover:scale-[1.02]"/></div><h3 className="mt-3 font-display text-2xl text-primary">{p.name}</h3><p className="text-sm text-muted-foreground">{p.fragranceFamily} · {p.subtitle}</p></Link>)}</div><div className="mt-10 flex flex-wrap gap-3"><Button asChild><Link href="/fragrance-finder/start">View Recommendations</Link></Button><Button asChild variant="outline" onClick={reset}><Link href="/fragrance-finder/start">Retake Finder</Link></Button></div></div>}
function Item({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-semibold uppercase tracking-wider text-aurevia-gold">{label}</dt><dd className="mt-2 capitalize text-primary">{value}</dd></div>}
