"use client"
import { zodResolver } from "@hookform/resolvers/zod"
import { useEffect, useState } from "react"
import { useForm } from "react-hook-form"
import { z } from "zod"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
const schema=z.object({fullName:z.string().trim().min(2,"Enter your full name."),phone:z.string().regex(/^$|^[+\d][\d\s-]{7,18}$/,"Enter a valid phone number.")});type Values=z.infer<typeof schema>
type Profile={fullName:string;email:string;phone:string;createdAt:string}
export default function ProfilePage(){const [profile,setProfile]=useState<Profile|null>(null),[editing,setEditing]=useState(false),[message,setMessage]=useState("");const {register,handleSubmit,reset,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(schema),defaultValues:{fullName:"",phone:""}});useEffect(()=>{fetch("/api/account/profile").then(async response=>{if(!response.ok)throw new Error();const data=await response.json() as Profile;setProfile(data);reset({fullName:data.fullName,phone:data.phone})}).catch(()=>setMessage("We couldn't load your profile. Please refresh the page."))},[reset]);async function save(values:Values){setMessage("");const response=await fetch("/api/account/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});if(!response.ok){setMessage("Your changes couldn't be saved. Please try again.");return}const data=await response.json() as Profile;setProfile(data);reset({fullName:data.fullName,phone:data.phone});setEditing(false);setMessage("Profile updated.")}return <div><p className="text-eyebrow text-aurevia-gold">Account details</p><h1 className="text-display mt-3 text-primary">Profile</h1>{message&&<p role="status" className="mt-5 text-success">{message}</p>}<form onSubmit={handleSubmit(save)} className="mt-8 max-w-2xl space-y-5"><div><Label htmlFor="fullName">Full name</Label><Input id="fullName" disabled={!editing||!profile} autoComplete="name" className="mt-2" {...register("fullName")}/>{errors.fullName&&<p role="alert" className="mt-1 text-sm text-destructive">{errors.fullName.message}</p>}</div><div><Label htmlFor="email">Email address</Label><Input id="email" value={profile?.email??""} readOnly disabled className="mt-2"/><p className="mt-1 text-xs text-muted-foreground">Email changes require verification and are handled by support.</p></div><div><Label htmlFor="phone">Phone number</Label><Input id="phone" disabled={!editing||!profile} type="tel" autoComplete="tel" className="mt-2" {...register("phone")}/>{errors.phone&&<p role="alert" className="mt-1 text-sm text-destructive">{errors.phone.message}</p>}</div><div><Label>Account created</Label><p className="mt-2 text-sm text-muted-foreground">{profile?.createdAt?new Intl.DateTimeFormat("en-NG",{dateStyle:"long"}).format(new Date(profile.createdAt)):"Loading…"}</p></div>{editing?<div className="flex gap-3"><Button disabled={isSubmitting}>{isSubmitting?"Saving…":"Save Changes"}</Button><Button type="button" variant="outline" onClick={()=>{reset({fullName:profile?.fullName??"",phone:profile?.phone??""});setEditing(false)}}>Cancel</Button></div>:<Button type="button" disabled={!profile} onClick={()=>setEditing(true)}>Edit Profile</Button>}</form></div>}
