import type { Metadata } from "next"
import { ArrowRight, Compass, Sparkles, WandSparkles } from "lucide-react"
import Image from "next/image"
import Link from "next/link"
import { ProductCard } from "@/components/storefront/product-card"
import { StoreLayout } from "@/components/storefront/store-layout"
import { Button } from "@/components/ui/button"
import { families, products } from "@/data/products"
export const metadata:Metadata={title:"Aurévia — Find a Fragrance That Feels Like You",description:"Discover curated perfumes, explore fragrance families, and find scents matched to your taste with Aurévia."}
const familyNotes:Record<string,string>={Floral:"Rose • Jasmine • Peony",Woody:"Cedar • Sandalwood • Vetiver",Amber:"Amber • Vanilla • Resin",Oud:"Oud • Suede • Amber",Citrus:"Mandarin • Grapefruit • Tea",Fresh:"Marine • Green • Musk"}
function Heading({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <div><p className="text-eyebrow text-aurevia-gold">{eyebrow}</p><h2 className="text-heading-1 mt-2 text-primary">{title}</h2>{copy&&<p className="mt-3 text-muted-foreground">{copy}</p>}</div>}
export default function HomePage(){const featured=products.filter(p=>p.isFeatured&&!p.isNew).slice(0,4),bestPool=products.filter(p=>p.isBestSeller),best=[...bestPool.filter(p=>!p.isNew).slice(0,2),...bestPool.filter(p=>p.isNew).slice(0,2)],newItems=products.filter(p=>p.isNew).slice(0,3),gifts=products.filter(p=>p.collection==="Gifting");return <StoreLayout><main><section className="relative min-h-[calc(100svh-5rem)] overflow-hidden bg-aurevia-plum text-aurevia-ivory lg:min-h-[calc(100vh-5rem)]"><video className="absolute inset-0 size-full object-cover object-[58%_center] motion-reduce:hidden sm:object-center" autoPlay muted loop playsInline preload="metadata" poster="/images/perfumes/velvet-ember/editorial.png" aria-hidden="true"><source src="/videos/aurevia-hero.mp4" type="video/mp4"/></video><div aria-hidden="true" className="absolute inset-0 hidden bg-[url('/images/perfumes/velvet-ember/editorial.png')] bg-cover bg-[position:58%_center] motion-reduce:block sm:bg-center"/><div className="absolute inset-0 bg-gradient-to-r from-aurevia-plum/80 via-aurevia-plum/35 to-transparent"/><div className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-b from-transparent to-aurevia-ivory/20"/><div className="aurevia-container relative flex min-h-[calc(100svh-5rem)] items-center py-20 lg:min-h-[calc(100vh-5rem)]"><div className="max-w-xl"><p className="text-eyebrow text-aurevia-gold">Aurévia</p><h1 className="mt-5 font-display text-[clamp(3.7rem,7vw,7rem)] font-medium leading-[.88]">Fragrance,<br/>remembered.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-aurevia-ivory/85">Discover fragrances created to leave a lasting impression.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-14 bg-aurevia-gold text-aurevia-charcoal"><Link href="/shop">Shop the Collection <ArrowRight/></Link></Button><Button asChild size="lg" variant="outline" className="h-14 border-aurevia-ivory/60 bg-transparent text-aurevia-ivory hover:bg-white/10 hover:text-white"><Link href="/fragrance-finder">Find Your Scent</Link></Button></div></div></div></section>
<section className="aurevia-container py-20"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><Heading eyebrow="Discover" title="Curated for you" copy="A considered edit of fragrances worth discovering."/><Link href="/shop" className="font-semibold text-primary underline-offset-4 hover:underline">View All →</Link></div><div className="mt-10 grid grid-cols-2 gap-x-4 gap-y-10 lg:grid-cols-4 lg:gap-7">{featured.map((p,i)=><ProductCard key={p.id} product={p} priority={i<2}/>)}</div></section>
<section id="families" className="bg-aurevia-cream py-20"><div className="aurevia-container"><Heading eyebrow="Explore by character" title="Shop by fragrance family"/><div className="mt-10 grid gap-px overflow-hidden border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{families.map(f=>{const p=products.find(item=>item.fragranceFamily===f&&Object.keys(item.images).length>1)??products.find(item=>item.fragranceFamily===f)!;return <Link key={f} href={`/shop?family=${f.toLowerCase()}`} className="group relative min-h-52 overflow-hidden bg-aurevia-ivory p-7"><Image src={p.images.ingredient??p.images.editorial??p.image} alt="" fill sizes="(max-width:640px) 100vw, (max-width:1024px) 50vw, 33vw" className="object-cover opacity-25 transition duration-300 group-hover:scale-105 group-hover:opacity-35"/><div className="absolute inset-0 bg-gradient-to-r from-aurevia-ivory/95 via-aurevia-ivory/65 to-transparent"/><div className="relative"><h3 className="font-display text-4xl text-primary">{f}</h3><p className="mt-2 text-sm text-muted-foreground">{familyNotes[f]}</p><ArrowRight className="mt-12 size-5 text-aurevia-gold"/></div></Link>})}</div></div></section>
<section className="grid bg-aurevia-plum text-aurevia-ivory lg:grid-cols-2"><div className="relative min-h-[32rem]"><Image src="/images/perfumes/velvet-ember/catalog.jpg" alt="Velvet Ember evening fragrance campaign" fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/></div><div className="flex items-center px-6 py-16 sm:px-12 lg:px-16"><div className="max-w-xl"><p className="text-eyebrow text-aurevia-gold">The editorial collection</p><h2 className="mt-3 font-display text-6xl">After Dark</h2><p className="mt-5 text-lg leading-8 text-aurevia-ivory/75">Deep woods, warm amber and lingering spice — fragrances made for evenings that stay with you.</p><Button asChild size="lg" className="mt-8 bg-aurevia-gold text-aurevia-charcoal"><Link href="/shop?collection=after-dark">Explore the Collection</Link></Button></div></div></section>
<section className="aurevia-container py-20"><div className="flex items-end justify-between"><Heading eyebrow="Most loved" title="Best Sellers"/><Link href="/shop?collection=best-sellers" className="hidden font-semibold text-primary underline sm:block">Shop Best Sellers</Link></div><div className="mt-10 grid grid-cols-2 gap-x-4 gap-y-10 lg:grid-cols-4 lg:gap-7">{best.map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
<section className="bg-aurevia-rose/25 py-20"><div className="aurevia-container grid items-center gap-12 lg:grid-cols-2"><div><p className="text-eyebrow text-aurevia-gold">Not sure where to start?</p><h2 className="text-heading-1 mt-3 text-primary">Meet your scent match.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-muted-foreground">Tell us what you naturally gravitate toward and we&apos;ll help narrow the collection to fragrances that feel right for you.</p><Button asChild size="lg" className="mt-7"><Link href="/fragrance-finder">Find My Scent <WandSparkles/></Link></Button></div><div className="relative min-h-80 overflow-hidden rounded-t-[8rem]"><Image src="/images/perfumes/fleur-de-lune/editorial.png" alt="Fleur de Lune perfume among luminous white flowers" fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/></div></div></section>
<section className="aurevia-container py-20"><Heading eyebrow="Just arrived" title="New Arrivals" copy="Fresh additions to the Aurévia collection."/><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{newItems.map((p,i)=><ProductCard key={p.id} product={p} priority={i===0} imageKind={p.images.ingredient?"ingredient":"editorial"}/>)}</div><Button asChild variant="outline" className="mt-10"><Link href="/shop?collection=new">Discover What&apos;s New</Link></Button></section>
<section className="bg-aurevia-cream py-20"><div className="aurevia-container"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-eyebrow text-aurevia-gold">For every occasion</p><h2 className="mt-2 font-display text-5xl text-primary sm:text-6xl">Gifts that tell a story.</h2><p className="mt-3 max-w-2xl text-muted-foreground">Two- and three-fragrance edits for partners, birthdays, anniversaries and meaningful milestones.</p></div><Link href="/shop?collection=gifting" className="font-semibold text-primary underline-offset-4 hover:underline">Shop All Gifts →</Link></div><div className="mt-10 grid gap-6 md:grid-cols-3">{gifts.map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
<section className="bg-aurevia-cream py-20"><div className="aurevia-container"><Heading eyebrow="The Aurévia way" title="Fragrance, made more personal."/><div className="mt-10 grid gap-8 md:grid-cols-3">{[[Compass,"Discover","Explore scents by mood, note and fragrance family."],[Sparkles,"Understand","Learn what you're smelling without confusing perfume jargon."],[WandSparkles,"Find Your Match","Use our scent discovery experience whenever you want guidance."]].map(([Icon,t,c])=><div key={String(t)} className="border-t border-aurevia-gold pt-6"><Icon className="size-5 text-aurevia-gold"/><h3 className="mt-5 font-display text-3xl text-primary">{String(t)}</h3><p className="mt-2 text-muted-foreground">{String(c)}</p></div>)}</div></div></section>
<section className="aurevia-container py-24 text-center"><h2 className="mx-auto max-w-3xl font-display text-5xl text-primary sm:text-6xl">Your next signature scent may be closer than you think.</h2><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild size="lg"><Link href="/shop">Shop All</Link></Button><Button asChild size="lg" variant="outline"><Link href="/fragrance-finder">Find My Scent</Link></Button></div></section></main></StoreLayout>}
