"use client"
import { Heart, MapPin, Package, Sparkles, UserRound } from "lucide-react"
import Image from "next/image"
import Link from "next/link"
import { formatPrice } from "@/data/products"
import { useAccountStore } from "@/store/account-store"
import { useOrderStore } from "@/store/order-store"
import { useWishlistStore } from "@/store/wishlist-store"
export default function AccountPage(){const profile=useAccountStore(s=>s.profile),addresses=useAccountStore(s=>s.addresses),orders=useOrderStore(s=>s.orders),slugs=useWishlistStore(s=>s.slugs),recent=orders[0],first=profile.fullName.trim().split(" ")[0];const cards=[[Heart,"Wishlist",`${slugs.length} saved fragrances`,"/wishlist"],[Sparkles,"Scent Profile","Discover what naturally suits you","/account/scent-profile"],[MapPin,"Addresses",addresses.find(a=>a.isDefault)?.city||"No default address yet","/account/addresses"],[UserRound,"Profile",profile.email||"Complete your details","/account/profile"]] as const;return <div><p className="text-eyebrow text-aurevia-gold">My Aurévia</p><h1 className="text-display mt-3 text-primary">Welcome back{first?`, ${first}`:""}.</h1><p className="mt-4 text-lg text-muted-foreground">Everything you love, saved in one place.</p>{recent?<section className="mt-10 grid gap-6 bg-aurevia-plum p-6 text-aurevia-ivory sm:p-8 md:grid-cols-[1fr_auto]"><div><p className="text-eyebrow text-aurevia-gold">Recent order</p><h2 className="mt-3 font-display text-3xl">{recent.orderNumber}</h2><p className="mt-2 text-sm text-aurevia-ivory/70">Confirmed · {formatPrice(recent.total)}</p><Link href={`/account/orders/${recent.id}`} className="mt-6 inline-block font-semibold underline">View Order</Link></div><div className="flex -space-x-3">{recent.items.slice(0,3).map(item=><Image key={item.lineId} src={item.image} alt="" width={80} height={100} className="h-24 w-20 border-2 border-aurevia-plum object-cover"/>)}</div></section>:<section className="mt-10 bg-aurevia-cream p-8"><Package className="size-6 text-aurevia-gold"/><h2 className="mt-4 font-display text-3xl text-primary">Your first order is waiting to be discovered.</h2><Link href="/shop" className="mt-5 inline-block font-semibold text-primary underline">Explore Fragrances</Link></section>}<div className="mt-8 grid gap-4 sm:grid-cols-2">{cards.map(([Icon,title,copy,href],i)=><Link key={title} href={href} className={`border-t border-aurevia-gold bg-aurevia-cream p-6 ${i===0?"sm:row-span-1":""}`}><Icon className="size-5 text-aurevia-gold"/><h2 className="mt-5 font-display text-3xl text-primary">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{copy}</p></Link>)}</div></div>}
